SystemOrganization addCategory: #'Telescope-Cytoscape-Tests'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Tests-Client'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Tests-Commands'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Tests-Connector'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Tests-Shape'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Tests-Virtual'!
