SystemOrganization addCategory: #'Telescope-Cytoscape'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Actions'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Commands'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Connector'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Demos'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Exception'!
SystemOrganization addCategory: 'Telescope-Cytoscape-Virtual'!
